USE VITALPRO;
GO
GRANT EXECUTE ON SP_SEGUIMIENTO_PROGRESO_FISICO TO admin_user;
GO
GRANT EXECUTE ON SP_RESERVAS_POR_PROFESIONAL_EN_UNA_SEMANA TO admin_user;
GO
GRANT EXECUTE ON SP_RUTINAS_ACTIVAS_POR_NIVEL TO admin_user;
GO
GRANT EXECUTE ON SP_RECETAS_MAS_UTILIZADAS_POR_TIPO_DE_PLAN TO admin_user;
GO
GRANT EXECUTE ON SP_CLIENTES_CON_MAYOR_ADERENCIAS TO admin_user;
GO
GRANT EXECUTE ON SP_ENTRENADOR_CON_EL_CENTRO TO admin_user;
GO
GRANT EXECUTE ON SP_NUTRICIONISTAS_CON_EL_CENTRO TO admin_user;
GO
GRANT EXECUTE ON SP_CLIENTES_SIN_ASISTENCIA_EL_ULTIMO_MES TO admin_user;
GO
GRANT EXECUTE ON SP_CLIENTES_SIN_EVALUACION TO admin_user;
GO
GRANT EXECUTE ON SP_SESIONES_CANCELADAS_POR_MES TO admin_user;
GO
GRANT EXECUTE ON SP_PLANES_ALIMENTICIOS_POR_NUTRICIONISTA TO admin_user;
GO
GRANT EXECUTE ON SP_EJERCICIOS_POR_RUTINA TO admin_user;
GO
GRANT EXECUTE ON SP_PROFESIONALES_SIN_SESIONES TO admin_user;
GO
GRANT EXECUTE ON SP_SESIONES_POR_ESTADO TO admin_user;
GO
GRANT EXECUTE ON SP_SEGUIMIENTO_PROGRESO_FISICO TO entrenador_user;
GO
GRANT EXECUTE ON SP_RUTINAS_ACTIVAS_POR_NIVEL TO entrenador_user;
GO
GRANT EXECUTE ON SP_CLIENTES_CON_MAYOR_ADERENCIAS TO entrenador_user;
GO
GRANT EXECUTE ON SP_ENTRENADOR_CON_EL_CENTRO TO entrenador_user;
GO
GRANT EXECUTE ON SP_CLIENTES_SIN_ASISTENCIA_EL_ULTIMO_MES TO entrenador_user;
GO
GRANT EXECUTE ON SP_CLIENTES_SIN_EVALUACION TO entrenador_user;
GO
GRANT EXECUTE ON SP_EJERCICIOS_POR_RUTINA TO entrenador_user;
GO
GRANT EXECUTE ON SP_SESIONES_POR_ESTADO TO entrenador_user;
GO
GRANT EXECUTE ON SP_RECETAS_MAS_UTILIZADAS_POR_TIPO_DE_PLAN TO nutricionista_user;
GO
GRANT EXECUTE ON SP_NUTRICIONISTAS_CON_EL_CENTRO TO nutricionista_user;
GO
GRANT EXECUTE ON SP_PLANES_ALIMENTICIOS_POR_NUTRICIONISTA TO nutricionista_user;
GO
GRANT EXECUTE ON SP_SEGUIMIENTO_PROGRESO_FISICO TO cliente_user;
GO
