USE VITALPRO
GO

-- ========== PERMISOS PARA PROFESIONAL ==========
GRANT EXECUTE ON SP_SEGUIMIENTO_PROGRESO_FISICO TO Profesional;
GRANT EXECUTE ON SP_RESERVAS_POR_PROFESIONAL_EN_UNA_SEMANA TO Profesional;
GRANT EXECUTE ON SP_CLIENTES_CON_MAYOR_ADERENCIAS TO Profesional;
GRANT EXECUTE ON SP_CLIENTES_SIN_ASISTENCIA_EL_ULTIMO_MES TO Profesional;
GO

-- ========== PERMISOS PARA ENTRENADOR ==========
GRANT EXECUTE ON SP_RUTINAS_ACTIVAS_POR_NIVEL TO Entrenador;
GRANT EXECUTE ON SP_ENTRENADOR_CON_EL_CENTRO TO Entrenador;
GO

-- ========== PERMISOS PARA NUTRICIONISTA ==========
GRANT EXECUTE ON SP_RECETAS_MAS_UTILIZADAS_POR_TIPO_DE_PLAN TO Nutricionista;
GRANT EXECUTE ON SP_NUTRICIONISTAS_CON_EL_CENTRO TO Nutricionista;
GO

-- ========== PERMISOS PARA CLIENTE ==========
GRANT EXECUTE ON SP_SEGUIMIENTO_PROGRESO_FISICO TO Cliente;
GRANT EXECUTE ON SP_RUTINAS_ACTIVAS_POR_NIVEL TO Cliente;
GRANT EXECUTE ON SP_RECETAS_MAS_UTILIZADAS_POR_TIPO_DE_PLAN TO Cliente;
GO

-- ========== PERMISOS PARA ADMINISTRADOR (TODOS) ==========
GRANT EXECUTE ON SP_SEGUIMIENTO_PROGRESO_FISICO TO Administrador;
GRANT EXECUTE ON SP_RESERVAS_POR_PROFESIONAL_EN_UNA_SEMANA TO Administrador;
GRANT EXECUTE ON SP_RUTINAS_ACTIVAS_POR_NIVEL TO Administrador;
GRANT EXECUTE ON SP_RECETAS_MAS_UTILIZADAS_POR_TIPO_DE_PLAN TO Administrador;
GRANT EXECUTE ON SP_CLIENTES_CON_MAYOR_ADERENCIAS TO Administrador;
GRANT EXECUTE ON SP_ENTRENADOR_CON_EL_CENTRO TO Administrador;
GRANT EXECUTE ON SP_NUTRICIONISTAS_CON_EL_CENTRO TO Administrador;
GRANT EXECUTE ON SP_CLIENTES_SIN_ASISTENCIA_EL_ULTIMO_MES TO Administrador;
GO
