-- Asignación de permisos para todos los procedimientos almacenados en VITALPRO

USE VITALPRO
GO

-- ========== PERMISOS PARA PROFESIONAL ==========
GRANT EXECUTE ON SP_SEGUIMIENTO_PROGRESO_FISICO TO Profesional;
GRANT EXECUTE ON SP_RESERVAS_POR_PROFESIONAL_EN_UNA_SEMANA TO Profesional;
GRANT EXECUTE ON SP_CLIENTES_CON_MAYOR_ADERENCIAS TO Profesional;
GRANT EXECUTE ON SP_CLIENTES_SIN_ASISTENCIA_EL_ULTIMO_MES TO Profesional;
GRANT EXECUTE ON SP_CLIENTES_SIN_EVALUACION TO Profesional;
GRANT EXECUTE ON SP_PROFESIONALES_SIN_SESIONES TO Profesional;
GRANT EXECUTE ON SP_SESIONES_POR_ESTADO TO Profesional;
GO

-- ========== PERMISOS PARA ENTRENADOR ==========
GRANT EXECUTE ON SP_RUTINAS_ACTIVAS_POR_NIVEL TO Entrenador;
GRANT EXECUTE ON SP_ENTRENADOR_CON_EL_CENTRO TO Entrenador;
GRANT EXECUTE ON SP_EJERCICIOS_POR_RUTINA TO Entrenador;
GO

-- ========== PERMISOS PARA NUTRICIONISTA ==========
GRANT EXECUTE ON SP_RECETAS_MAS_UTILIZADAS_POR_TIPO_DE_PLAN TO Nutricionista;
GRANT EXECUTE ON SP_NUTRICIONISTAS_CON_EL_CENTRO TO Nutricionista;
GRANT EXECUTE ON SP_PLANES_ALIMENTICIOS_POR_NUTRICIONISTA TO Nutricionista;
GO

-- ========== PERMISOS PARA CLIENTE ==========
GRANT EXECUTE ON SP_SEGUIMIENTO_PROGRESO_FISICO TO Cliente;
GRANT EXECUTE ON SP_RUTINAS_ACTIVAS_POR_NIVEL TO Cliente;
GRANT EXECUTE ON SP_RECETAS_MAS_UTILIZADAS_POR_TIPO_DE_PLAN TO Cliente;
GRANT EXECUTE ON SP_SESIONES_POR_ESTADO TO Cliente;
GO

-- ========== PERMISOS PARA ADMINISTRADOR (TODOS) ==========
GRANT EXECUTE ON SP_SEGUIMIENTO_PROGRESO_FISICO TO Administrador;
GRANT EXECUTE ON SP_RESERVAS_POR_PROFESIONAL_EN_UNA_SEMANA TO Administrador;
GRANT EXECUTE ON SP_RUTINAS_ACTIVAS_POR_NIVEL TO Administrador;
GRANT EXECUTE ON SP_RECETAS_MAS_UTILIZADAS_POR_TIPO_DE_PLAN TO Administrador;
GRANT EXECUTE ON SP_CLIENTES_CON_MAYOR_ADERENCIAS TO Administrador;
GRANT EXECUTE ON SP_ENTRENADOR_CON_EL_CENTRO TO Administrador;
GRANT EXECUTE ON SP_NUTRICIONISTAS_CON_EL_CENTRO TO Administrador;
GRANT EXECUTE ON SP_CLIENTES_SIN_ASISTENCIA_EL_ULTIMO_MES TO Administrador;
GRANT EXECUTE ON SP_CLIENTES_SIN_EVALUACION TO Administrador;
GRANT EXECUTE ON SP_SESIONES_CANCELADAS_POR_MES TO Administrador;
GRANT EXECUTE ON SP_PLANES_ALIMENTICIOS_POR_NUTRICIONISTA TO Administrador;
GRANT EXECUTE ON SP_EJERCICIOS_POR_RUTINA TO Administrador;
GRANT EXECUTE ON SP_PROFESIONALES_SIN_SESIONES TO Administrador;
GRANT EXECUTE ON SP_SESIONES_POR_ESTADO TO Administrador;
GO